development:
  adapter: postgresql
  encoding: utf8
  database: subscription
  host: localhost
  username: arrivu
  password: arrivu
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: subscription
  host: localhost
  username: arrivu
  password: arrivu
  timeout: 5000
